### ISSUE TITLE
Fail to build when upgrade to v5.1.3

### ISSUE THREAD

**Issue by GZTimeWalker** [mantinedev/mantine#2080]
### What package has an issue

@mantine/dropzone

### Describe the bug

when I upgrade the package to v5.1.3 from v5.1.1, vite build fails because of:

"Failed to load plugin 'prettier' declared in 'node_modules\.pnpm\react-dropzone@14.2.1_react@18.2.0\node_modules\react-dropzone\.eslintrc': Cannot find module 'eslint-plugin-prettier'"

I'm trying to add following packages:
```
"eslint-config-prettier": "^8.5.0",
"eslint-plugin-import": "^2.26.0",
"eslint-plugin-node": "^11.1.0",
"eslint-plugin-prettier": "^4.2.1",
```

but then I got "Failed to load config "okonet" to extend from.", I don't know how to deal with it.

I noticed that "react-dropzone" has not been updated recently, and "@mantine/dropzone"  has not updated the referenced version, so I guess I can get the answer here.

### What version of @mantine/hooks page do you have in package.json?

^5.1.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @GZTimeWalker, your issue is not related to Mantine, something went wrong during node_module installation. As I can tell the issue is that `eslint-plugin-prettier` was not installed. I recommend to use yarn or npm for packages installation.
