### ISSUE TITLE
Cannot find module '@emotion/server/create-instance' after upgrade to ˆ5.0.3 

### ISSUE THREAD

**Issue by rafae2k** [mantinedev/mantine#2438]
### What package has an issue

@mantine/core

### Describe the bug

After upgrading from 4.2 to 5.0.3 we get into this error:

cannot find module '@emotion/server/create-instance'

``` sh
Require stack:
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/@mantine/ssr/cjs/create-styles-server.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/@mantine/ssr/cjs/index.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/@mantine/next/cjs/index.js
- /Users/rafo/code/work/bewex/bewex-main-app/.next/server/pages/_document.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/server/require.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/server/load-components.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/build/utils.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/build/output/store.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/build/output/index.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/cli/next-dev.js
- /Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.mod._resolveFilename (/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/rafo/code/work/bewex/bewex-main-app/node_modules/@mantine/ssr/cjs/create-styles-server.js:5:27)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/@mantine/ssr/cjs/create-styles-server.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/@mantine/ssr/cjs/index.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/@mantine/next/cjs/index.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/.next/server/pages/_document.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/server/require.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/server/load-components.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/build/utils.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/build/output/store.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/build/output/index.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/cli/next-dev.js',
    '/Users/rafo/code/work/bewex/bewex-main-app/node_modules/next/dist/bin/next'
  ]
}
```

### What version of @mantine/hooks page do you have in package.json?

5.3.0

### If possible, please include a link to a codesandbox with the reproduced problem

n/a

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

don't know yet

**Comment by rtivital** [comment]
You need to install `@emotion/react` and `@emotion/server` packages, see changelog – https://mantine.dev/changelog/5-0-0/#emotion-packages-as-peer-dependencies
