### ISSUE TITLE
Property 'placeholder' does not exist on DatePickerInput

### ISSUE THREAD

**Issue by GZTimeWalker** [mantinedev/mantine#5401]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6.0.21

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

After upgrade to v6.0.21, my project cannot pass the `tsc` check with error: 

```log
Property 'placeholder' does not exist on type 'IntrinsicAttributes & DatePickerInputProps<"default">'.
```

I checked the docs, this property still on the demo:

```tsx
import { MantineProvider } from "@mantine/core";
import { useState } from "react";
import { DatePickerInput } from "@mantine/dates";

function Demo() {
  const [value, setValue] = useState<Date | null>(null);
  return (
    <DatePickerInput
      label="Pick date"
      placeholder="Pick date"
      value={value}
      onChange={setValue}
      mx="auto"
      maw={400}
    />
  );
}

export default function App() {
  return (
    <MantineProvider>
      <Demo />
    </MantineProvider>
  );
}
```

This demo can also get this error:

```log
src/App.tsx:10:7 - error TS2322: Type '{ label: string; placeholder: string; value: Date | null; onChange: Dispatch<SetStateAction<Date | null>>; mx: "auto"; maw: number; }' is not assignable to type 'IntrinsicAttributes & DatePickerInputProps<"default">'.
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & DatePickerInputProps<"default">'.

10       placeholder="Pick date"
         ~~~~~~~~~~~
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/gracious-euler-t7r4qy

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I cannot reproduce the issue on codesandbox – https://codesandbox.io/p/sandbox/cocky-bessie-w4754k?file=%2Fsrc%2FApp.tsx%3A9%2C47

Most likely, the issue is somewhere in your project, try reinstalling dependencies.

**Comment by GZTimeWalker** [comment]
> I cannot reproduce the issue on codesandbox – [codesandbox.io/p/sandbox/cocky-bessie-w4754k?file=%2Fsrc%2FApp.tsx%3A9%2C47](https://codesandbox.io/p/sandbox/cocky-bessie-w4754k?file=%2Fsrc%2FApp.tsx%3A9%2C47)
> 
> Most likely, the issue is somewhere in your project, try reinstalling dependencies.

I also **cannot reproduce the issue on codesandbox**, and note **this issue is on the mantine v6**.

I tried this minimal example on different environment, it's the same.

[mantine-example.zip](https://github.com/mantinedev/mantine/files/13626896/mantine-example.zip)

**Comment by GZTimeWalker** [comment]
And make sure the `tsc` was called for this type check.

**Comment by GZTimeWalker** [comment]
OK, here is the codesandbox example:

https://codesandbox.io/p/sandbox/gracious-euler-t7r4qy

**Comment by rtivital** [comment]
It is not planned to release patched for 6.x versions. I can only recommend to disable type checking for this case
```tsx
import { DatePickerInput as _DatePickerInput } from "@mantine/dates";

const DatePickerInput = _DatePickerInput as any;
```

**Comment by GZTimeWalker** [comment]
> It is not planned to release patched for 6.x versions. I can only recommend to disable type checking for this case

I wonder why this issue wasn't in the previous version, or what caused this issue to be introduced?

**Comment by GZTimeWalker** [comment]
In my own usage scenario, simply removing this property would be the best solution.

As a suggestion, perhaps it would be best to remove it from the documentation?

**Comment by simeq** [comment]
@rtivital Got the same error with `@mantine` `7.3.1` after upgrading to `@types/react` to `18.2.43`

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by finico** [comment]
recommendations to disable type checking or put `any` somewhere else are unreasonable
for those who still in v6

```ts
declare module '@mantine/core' {
    interface InputSharedProps {
        placeholder?: string | undefined;
    }

    interface ScrollAreaProps {
        placeholder?: string | undefined;
    }
}
```

**Comment by JuanLuisGarciaBorrego** [comment]
It also happens with component FileInput of version 5. 
It has always worked until a few days ago.

The solution 

```javascript
import { FileInput as _FileInput } from '@mantine/core'

const FileInput = _FileInput as any
```

**Comment by spicybackend** [comment]
Another workaround without losing or disabling types is to spread the placeholder prop in,

```tsx
<DatePickerInput
  label="My date picker"
  {...{ placeholder: "Pick a date" }}
  value={value}
  onChange={onChange}
/>
```

**Comment by rtivital** [comment]
Fixed in [7.4.0](https://github.com/mantinedev/mantine/releases/tag/7.4.0)

**Comment by GZTimeWalker** [comment]
Hi! Any backport for this issue to v6?

**Comment by rtivital** [comment]
I'm not planning to backport this, you can downgrade `@types/react` instead
