### PR TITLE
Update InputWrapper.tsx to fix #5401

### LINKED ISSUE #5401: Property 'placeholder' does not exist on DatePickerInput
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6.0.21

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

After upgrade to v6.0.21, my project cannot pass the `tsc` check with error: 

```log
Property 'placeholder' does not exist on type 'IntrinsicAttributes & DatePickerInputProps<"default">'.
```

I checked the docs, this property still on the demo:

```tsx
import { MantineProvider } from "@mantine/core";
import { useState } from "react";
import { DatePickerInput } from "@mantine/dates";

function Demo() {
  const [value, setValue] = useState<Date | null>(null);
  return (
    <DatePickerInput
      label="Pick date"
      placeholder="Pick date"
      value={value}
      onChange={setValue}
      mx="auto"
      maw={400}
    />
  );
}

export default function App() {
  return (
    <MantineProvider>
      <Demo />
    </MantineProvider>
  );
}
```

This demo can also get this error:

```log
src/App.tsx:10:7 - error TS2322: Type '{ label: string; placeholder: string; value: Date | null; onChange: Dispatch<SetStateAction<Date | null>>; mx: "auto"; maw: number; }' is not assignable to type 'IntrinsicAttributes & DatePickerInputProps<"default">'.
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & DatePickerInputProps<"default">'.

10       placeholder="Pick date"
         ~~~~~~~~~~~
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/gracious-euler-t7r4qy

### Possible fix

_No response_

### Self-service

- [ ] I would be willing to implement a fix for this issue

### PR DESCRIPTION
**Pull request by israelins85**
fix #5401

### CODE REVIEW

**Comment by rtivital** [comment]
It is not a valid fix. Placeholder type may vary across components. For example, TextInput component which uses Input.Wrapper, supports only string placeholders.

**Comment by israelins85** [comment]
@rtivital ok, where I have to put that type React.ReactNode?
